# Generated by Django 3.2.2 on 2021-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RussellData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TICKER', models.CharField(max_length=20)),
                ('D_DATE', models.DateField()),
                ('OPEN', models.DecimalField(decimal_places=5, max_digits=15)),
                ('HIGH', models.DecimalField(decimal_places=5, max_digits=15)),
                ('LOW', models.DecimalField(decimal_places=5, max_digits=15)),
                ('CLOSE', models.DecimalField(decimal_places=5, max_digits=15)),
                ('ADJ_CLOSE', models.DecimalField(decimal_places=5, max_digits=15)),
                ('VOLUME', models.IntegerField(max_length=15)),
            ],
        ),
    ]
